services:
    webapp:
        platform: linux/amd64
        build:
            context: .
            dockerfile: dockerfile
        image: consoleages:latest
        ports:
            - "2480:80"
        volumes:
            - ./public/:/usr/share/nginx/html/