version: '3'
services:
  vxml:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: consoleages:latest
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./public/:/usr/share/nginx/html/